### ISSUE TITLE
Import of DSFRecord fails

### ISSUE THREAD

**Issue by imneo1** [dyninc/dyn-python#43]
The import of DSFRecord fails:

from dyn.tm.services.dsf import DSFRecord, DSFRecordSet, DSFFailoverChain, 
DSFResponsePool, DSFRuleset, DSFMonitor, TrafficDirector

I reinstalled module with pip and then from clone.
reinstalled python 2.7 and installed again

still can't import it

**Comment by imneo1** [comment]
Also tried from another Fedora 21 and Centos 6.6
also tried older version on all machines:
https://pypi.python.org/packages/source/d/dyn/dyn-1.3.11.tar.gz

same result

**Comment by Marchowes** [comment]
This is working as designed. We have no DSFRecords. We have a private class called _DSFRecords however. In what context were you planning to use this?

We do have specific records types. See: http://dyn.readthedocs.org/en/latest/tm/services/dsf/dsf.html
