### ISSUE TITLE
Importing Zone fails in Python 3

### ISSUE THREAD

**Issue by przemal** [dyninc/dyn-python#80]
I think [someone](https://github.com/dyninc/dyn-python/commit/ce2f733f892560242eeddc422e29a058b3dafb15) forgot to cleanup print statement and now importing zone in Python 3 fails with syntax error ;)

Version 1.6.3

**Comment by grantholly** [comment]
I made a pull request that fixes this issue 

https://github.com/dyninc/dyn-python/pull/82

**Comment by whisk3y** [comment]
Merged the PR, we will be doing a new release (1.6.4) this week with that change and a couple other improvements as well.

**Comment by Marchowes** [comment]
fixed.
